package lcs.android.news;

public enum NewsEvent {
  ARMY_ARMORY,
  ARSON,
  ATTACKED,
  ATTACKED_MISTAKE,
  BREAK_FACTORY,
  BREAK_SWEATSHOP,
  BROKE_DOWN_DOOR,
  CARCHASE,
  CARCRASH,
  CORP_FILES,
  COURTHOUSE_LOCKUP,
  FOOT_CHASE,
  FREE_BEASTS,
  FREE_RABBITS,
  HACK_INTEL,
  HOUSE_PHOTOS,
  JURY_TAMPERING,
  KILLED_SOMEBODY,
  POLICE_LOCKUP,
  PRISON_RELEASE,
  SHUTDOWN_REACTOR,
  STOLE_GROUND,
  TAGGING,
  UNLOCKED_DOOR;
}