package lcs.android.news;

public enum StoryType {
  BURIALARREST,
  CARTHEFT,
  CCS_DEFENDED,
  CCS_KILLED_SIEGEATTACK,
  CCS_KILLED_SITE,
  CCS_SITE,
  DRUGARREST,
  GRAFFITIARREST,
  KIDNAPREPORT,
  MAJOREVENT,
  MASSACRE,
  NUDITYARREST,
  SQUAD_BROKESIEGE,
  SQUAD_DEFENDED,
  SQUAD_ESCAPED,
  SQUAD_FLEDATTACK,
  SQUAD_KILLED_SIEGEATTACK,
  SQUAD_KILLED_SIEGEESCAPE,
  SQUAD_KILLED_SITE,
  SQUAD_SITE,
  WANTEDARREST,
  NO_STORY
}
